/** @file
  Copyright (C) 2019-2020, vit9696. All rights reserved.

  All rights reserved.

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
**/

///
/// This file generated by PlistToConfig.py from Template.plist, do not edit
///

#include "BhConfig.h"

// STRUCT parent=struct
OC_STRUCTORS       (BH_CONFIG_CONFIG, ())

// ARRAY of=string parent=struct
OC_ARRAY_STRUCTORS (BH_MISC_BLESS_ARRAY)
// STRUCT parent=struct
OC_STRUCTORS       (BH_MISC_BOOT, ())
// STRUCT parent=struct
OC_STRUCTORS       (BH_MISC_DEBUG, ())
// STRUCT parent=array xref=BH_MISC_TOOLS_ENTRY
// ARRAY of=struct parent=struct xref=BH_MISC_TOOLS_ARRAY
// STRUCT parent=struct
OC_STRUCTORS       (BH_MISC_SECURITY, ())
// STRUCT parent=array
OC_STRUCTORS       (BH_MISC_TOOLS_ENTRY, ())
// ARRAY of=struct parent=struct
OC_ARRAY_STRUCTORS (BH_MISC_TOOLS_ARRAY)
// STRUCT parent=struct
OC_STRUCTORS       (BH_MISC_CONFIG, ())

// MAP of=map
OC_MAP_STRUCTORS   (BH_NVRAM_ADD_MAP)
// ARRAY of=string parent=map
OC_STRUCTORS       (BH_NVRAM_DELETE_ENTRY, ())
// MAP of=array
OC_MAP_STRUCTORS   (BH_NVRAM_DELETE_MAP)
// ARRAY of=string parent=map
OC_STRUCTORS       (BH_NVRAM_LEGACY_ENTRY, ())
// MAP of=array
OC_MAP_STRUCTORS   (BH_NVRAM_LEGACY_MAP)
// STRUCT parent=struct
OC_STRUCTORS       (BH_NVRAM_CONFIG, ())

// STRUCT parent=map
OC_STRUCTORS       (BH_GLOBAL_CONFIG, ())

//
// Config configuration support
//

// STRUCT parent=struct
STATIC
OC_SCHEMA
mConfigConfigurationSchema[] = {
  OC_SCHEMA_STRING_IN   ("PickerMode",              BH_GLOBAL_CONFIG,  Config.PickerMode),
  OC_SCHEMA_BOOLEAN_IN  ("PollAppleHotKeys",        BH_GLOBAL_CONFIG,  Config.PollAppleHotKeys),
  OC_SCHEMA_BOOLEAN_IN  ("ShowPicker",              BH_GLOBAL_CONFIG,  Config.ShowPicker),
  OC_SCHEMA_STRING_IN   ("Xanana",                  BH_GLOBAL_CONFIG,  Config.Xanana),
};

//
// Misc configuration support
//

// ARRAY of=string parent=struct
STATIC
OC_SCHEMA
mMiscBlessOverrideSchema = OC_SCHEMA_STRING (NULL);

// STRUCT parent=struct
STATIC
OC_SCHEMA
mMiscConfigurationBootSchema[] = {
  OC_SCHEMA_INTEGER_IN  ("ConsoleAttributes",       BH_GLOBAL_CONFIG,  Misc.Boot.ConsoleAttributes),
  OC_SCHEMA_STRING_IN   ("HibernateMode",           BH_GLOBAL_CONFIG,  Misc.Boot.HibernateMode),
  OC_SCHEMA_BOOLEAN_IN  ("HideAuxiliary",           BH_GLOBAL_CONFIG,  Misc.Boot.HideAuxiliary),
  OC_SCHEMA_INTEGER_IN  ("PickerAttributes",        BH_GLOBAL_CONFIG,  Misc.Boot.PickerAttributes),
  OC_SCHEMA_BOOLEAN_IN  ("PickerAudioAssist",       BH_GLOBAL_CONFIG,  Misc.Boot.PickerAudioAssist),
  OC_SCHEMA_STRING_IN   ("PickerMode",              BH_GLOBAL_CONFIG,  Misc.Boot.PickerMode),
  OC_SCHEMA_BOOLEAN_IN  ("PollAppleHotKeys",        BH_GLOBAL_CONFIG,  Misc.Boot.PollAppleHotKeys),
  OC_SCHEMA_BOOLEAN_IN  ("ShowPicker",              BH_GLOBAL_CONFIG,  Misc.Boot.ShowPicker),
  OC_SCHEMA_INTEGER_IN  ("TakeoffDelay",            BH_GLOBAL_CONFIG,  Misc.Boot.TakeoffDelay),
  OC_SCHEMA_INTEGER_IN  ("Timeout",                 BH_GLOBAL_CONFIG,  Misc.Boot.Timeout),
};

// STRUCT parent=struct
STATIC
OC_SCHEMA
mMiscConfigurationDebugSchema[] = {
  OC_SCHEMA_BOOLEAN_IN  ("AppleDebug",              BH_GLOBAL_CONFIG,  Misc.Debug.AppleDebug),
  OC_SCHEMA_BOOLEAN_IN  ("ApplePanic",              BH_GLOBAL_CONFIG,  Misc.Debug.ApplePanic),
  OC_SCHEMA_BOOLEAN_IN  ("DisableWatchDog",         BH_GLOBAL_CONFIG,  Misc.Debug.DisableWatchDog),
  OC_SCHEMA_INTEGER_IN  ("DisplayDelay",            BH_GLOBAL_CONFIG,  Misc.Debug.DisplayDelay),
  OC_SCHEMA_INTEGER_IN  ("DisplayLevel",            BH_GLOBAL_CONFIG,  Misc.Debug.DisplayLevel),
  OC_SCHEMA_BOOLEAN_IN  ("SerialInit",              BH_GLOBAL_CONFIG,  Misc.Debug.SerialInit),
  OC_SCHEMA_BOOLEAN_IN  ("SysReport",               BH_GLOBAL_CONFIG,  Misc.Debug.SysReport),
  OC_SCHEMA_INTEGER_IN  ("Target",                  BH_GLOBAL_CONFIG,  Misc.Debug.Target),
};

// STRUCT parent=array xref=BH_MISC_TOOLS_ENTRY
STATIC
OC_SCHEMA
mMiscEntriesSchemaEntry[] = {
  OC_SCHEMA_STRING_IN   ("Arguments",               BH_MISC_TOOLS_ENTRY, Arguments),
  OC_SCHEMA_BOOLEAN_IN  ("Auxiliary",               BH_MISC_TOOLS_ENTRY, Auxiliary),
  OC_SCHEMA_STRING_IN   ("Comment",                 BH_MISC_TOOLS_ENTRY, Comment),
  OC_SCHEMA_BOOLEAN_IN  ("Enabled",                 BH_MISC_TOOLS_ENTRY, Enabled),
  OC_SCHEMA_STRING_IN   ("Name",                    BH_MISC_TOOLS_ENTRY, Name),
  OC_SCHEMA_STRING_IN   ("Path",                    BH_MISC_TOOLS_ENTRY, Path),
  OC_SCHEMA_BOOLEAN_IN  ("TextMode",                BH_MISC_TOOLS_ENTRY, TextMode),
};

// ARRAY of=struct parent=struct xref=BH_MISC_TOOLS_ARRAY
STATIC
OC_SCHEMA
mMiscEntriesSchema = OC_SCHEMA_DICT (NULL, mMiscEntriesSchemaEntry);

// STRUCT parent=struct
STATIC
OC_SCHEMA
mMiscConfigurationSecuritySchema[] = {
  OC_SCHEMA_BOOLEAN_IN  ("AllowNvramReset",         BH_GLOBAL_CONFIG,  Misc.Security.AllowNvramReset),
  OC_SCHEMA_BOOLEAN_IN  ("AllowSetDefault",         BH_GLOBAL_CONFIG,  Misc.Security.AllowSetDefault),
  OC_SCHEMA_INTEGER_IN  ("ApECID",                  BH_GLOBAL_CONFIG,  Misc.Security.ApECID),
  OC_SCHEMA_BOOLEAN_IN  ("AuthRestart",             BH_GLOBAL_CONFIG,  Misc.Security.AuthRestart),
  OC_SCHEMA_BOOLEAN_IN  ("BlacklistAppleUpdate",    BH_GLOBAL_CONFIG,  Misc.Security.BlacklistAppleUpdate),
  OC_SCHEMA_STRING_IN   ("BootProtect",             BH_GLOBAL_CONFIG,  Misc.Security.BootProtect),
  OC_SCHEMA_STRING_IN   ("DmgLoading",              BH_GLOBAL_CONFIG,  Misc.Security.DmgLoading),
  OC_SCHEMA_BOOLEAN_IN  ("EnablePassword",          BH_GLOBAL_CONFIG,  Misc.Security.EnablePassword),
  OC_SCHEMA_INTEGER_IN  ("ExposeSensitiveData",     BH_GLOBAL_CONFIG,  Misc.Security.ExposeSensitiveData),
  OC_SCHEMA_INTEGER_IN  ("HaltLevel",               BH_GLOBAL_CONFIG,  Misc.Security.HaltLevel),
  OC_SCHEMA_DATAF_IN    ("PasswordHash",            BH_GLOBAL_CONFIG,  Misc.Security.PasswordHash),
  OC_SCHEMA_DATA_IN     ("PasswordSalt",            BH_GLOBAL_CONFIG,  Misc.Security.PasswordSalt),
  OC_SCHEMA_INTEGER_IN  ("ScanPolicy",              BH_GLOBAL_CONFIG,  Misc.Security.ScanPolicy),
  OC_SCHEMA_STRING_IN   ("SecureBootModel",         BH_GLOBAL_CONFIG,  Misc.Security.SecureBootModel),
  OC_SCHEMA_STRING_IN   ("Vault",                   BH_GLOBAL_CONFIG,  Misc.Security.Vault),
};

// STRUCT parent=array
STATIC
OC_SCHEMA
mMiscToolsSchemaEntry[] = {
  OC_SCHEMA_STRING_IN   ("Arguments",               BH_MISC_TOOLS_ENTRY, Arguments),
  OC_SCHEMA_BOOLEAN_IN  ("Auxiliary",               BH_MISC_TOOLS_ENTRY, Auxiliary),
  OC_SCHEMA_STRING_IN   ("Comment",                 BH_MISC_TOOLS_ENTRY, Comment),
  OC_SCHEMA_BOOLEAN_IN  ("Enabled",                 BH_MISC_TOOLS_ENTRY, Enabled),
  OC_SCHEMA_STRING_IN   ("Name",                    BH_MISC_TOOLS_ENTRY, Name),
  OC_SCHEMA_STRING_IN   ("Path",                    BH_MISC_TOOLS_ENTRY, Path),
  OC_SCHEMA_BOOLEAN_IN  ("RealPath",                BH_MISC_TOOLS_ENTRY, RealPath),
  OC_SCHEMA_BOOLEAN_IN  ("TextMode",                BH_MISC_TOOLS_ENTRY, TextMode),
};

// ARRAY of=struct parent=struct
STATIC
OC_SCHEMA
mMiscToolsSchema = OC_SCHEMA_DICT (NULL, mMiscToolsSchemaEntry);

// STRUCT parent=struct
STATIC
OC_SCHEMA
mMiscConfigurationSchema[] = {
  OC_SCHEMA_ARRAY_IN    ("BlessOverride",           BH_GLOBAL_CONFIG,  Misc.BlessOverride, &mMiscBlessOverrideSchema),
  OC_SCHEMA_DICT        ("Boot",                    mMiscConfigurationBootSchema),
  OC_SCHEMA_DICT        ("Debug",                   mMiscConfigurationDebugSchema),
  OC_SCHEMA_ARRAY_IN    ("Entries",                 BH_GLOBAL_CONFIG,  Misc.Entries, &mMiscEntriesSchema),
  OC_SCHEMA_DICT        ("Security",                mMiscConfigurationSecuritySchema),
  OC_SCHEMA_ARRAY_IN    ("Tools",                   BH_GLOBAL_CONFIG,  Misc.Tools, &mMiscToolsSchema),
};

//
// NVRAM configuration support
//

// MAP OF map OF blob, SUB-TYPE
STATIC
OC_SCHEMA
mNvramAddSchemaEntry = OC_SCHEMA_MDATA (NULL);

// MAP of=map
STATIC
OC_SCHEMA
mNvramAddSchema = OC_SCHEMA_MAP (NULL, &mNvramAddSchemaEntry);

// ARRAY of=string parent=map
// MAP OF array OF string, SUB-TYPE
STATIC
OC_SCHEMA
mNvramDeleteSchemaEntry = OC_SCHEMA_STRING (NULL);

// MAP of=array
STATIC
OC_SCHEMA
mNvramDeleteSchema = OC_SCHEMA_ARRAY (NULL, &mNvramDeleteSchemaEntry);

// ARRAY of=string parent=map
// MAP OF array OF string, SUB-TYPE
STATIC
OC_SCHEMA
mNvramLegacySchemaEntry = OC_SCHEMA_STRING (NULL);

// MAP of=array
STATIC
OC_SCHEMA
mNvramLegacySchema = OC_SCHEMA_ARRAY (NULL, &mNvramLegacySchemaEntry);

// STRUCT parent=struct
STATIC
OC_SCHEMA
mNvramConfigurationSchema[] = {
  OC_SCHEMA_MAP_IN      ("Add",                     BH_GLOBAL_CONFIG,  Nvram.Add, &mNvramAddSchema),
  OC_SCHEMA_MAP_IN      ("Delete",                  BH_GLOBAL_CONFIG,  Nvram.Delete, &mNvramDeleteSchema),
  OC_SCHEMA_BOOLEAN_IN  ("LegacyEnable",            BH_GLOBAL_CONFIG,  Nvram.LegacyEnable),
  OC_SCHEMA_BOOLEAN_IN  ("LegacyOverwrite",         BH_GLOBAL_CONFIG,  Nvram.LegacyOverwrite),
  OC_SCHEMA_MAP_IN      ("LegacySchema",            BH_GLOBAL_CONFIG,  Nvram.Legacy, &mNvramLegacySchema),
  OC_SCHEMA_BOOLEAN_IN  ("WriteFlash",              BH_GLOBAL_CONFIG,  Nvram.WriteFlash),
};

//
// Root configuration
//

// STRUCT parent=map
STATIC
OC_SCHEMA
mRootConfigurationNodes[] = {
  OC_SCHEMA_DICT        ("Config",                  mConfigConfigurationSchema),
  OC_SCHEMA_DICT        ("Misc",                    mMiscConfigurationSchema),
  OC_SCHEMA_DICT        ("NVRAM",                   mNvramConfigurationSchema),
};

STATIC
OC_SCHEMA_INFO
mRootConfigurationInfo = {
 .Dict = {mRootConfigurationNodes, ARRAY_SIZE (mRootConfigurationNodes)}
};

EFI_STATUS
BhConfigurationInit (
  OUT BH_GLOBAL_CONFIG   *Config,
  IN  VOID               *Buffer,
  IN  UINT32             Size
  )
{
  BOOLEAN   Success;
  UINT32    ErrorCount;

  BH_GLOBAL_CONFIG_CONSTRUCT (Config, sizeof (*Config));
  Success = ParseSerialized (Config, &mRootConfigurationInfo, Buffer, Size, &ErrorCount);

  if (!Success) {
    BH_GLOBAL_CONFIG_DESTRUCT (Config, sizeof (*Config));
    return EFI_UNSUPPORTED;
  }

  return EFI_SUCCESS;
}

VOID
BhConfigurationFree (
  IN OUT BH_GLOBAL_CONFIG   *Config
  )
{
  BH_GLOBAL_CONFIG_DESTRUCT (Config, sizeof (*Config));
}
