/** @file
  Copyright (C) 2019-2020, vit9696. All rights reserved.

  All rights reserved.

  This program and the accompanying materials
  are licensed and made available under the terms and conditions of the BSD License
  which accompanies this distribution.  The full text of the license may be found at
  http://opensource.org/licenses/bsd-license.php

  THE PROGRAM IS DISTRIBUTED UNDER THE BSD LICENSE ON AN "AS IS" BASIS,
  WITHOUT WARRANTIES OR REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
**/

///
/// This file generated by PlistToConfig.py from Template.plist, do not edit
///

#ifndef BH_CONFIGURATION_LIB_H
#define BH_CONFIGURATION_LIB_H

#include <Library/DebugLib.h>
#include <Library/OcSerializeLib.h>
#include <Library/OcBootManagementLib.h>
#include <Library/OcConfigurationLib.h>

/**
  Config section
**/

// STRUCT parent=struct
#define BH_CONFIG_CONFIG_FIELDS(_, __) \
  _(OC_STRING                       , PickerMode              ,     , OC_STRING_CONSTR ("Builtin", _, __) , OC_DESTR (OC_STRING) ) \
  _(BOOLEAN                         , PollAppleHotKeys        ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , ShowPicker              ,     , FALSE                               , ())                    \
  _(OC_STRING                       , Xanana                  ,     , OC_STRING_CONSTR ("", _, __)        , OC_DESTR (OC_STRING) )
  OC_DECLARE (BH_CONFIG_CONFIG)

/**
  Misc section
**/

// ARRAY of=string parent=struct
#define BH_MISC_BLESS_ARRAY_FIELDS(_, __) \
  OC_ARRAY (OC_STRING, _, __)
  OC_DECLARE (BH_MISC_BLESS_ARRAY)

// STRUCT parent=struct
#define BH_MISC_BOOT_FIELDS(_, __) \
  _(UINT32                          , ConsoleAttributes       ,     , 0                                   , ())                    \
  _(OC_STRING                       , HibernateMode           ,     , OC_STRING_CONSTR ("None", _, __)    , OC_DESTR (OC_STRING) ) \
  _(BOOLEAN                         , HideAuxiliary           ,     , FALSE                               , ())                    \
  _(UINT32                          , PickerAttributes        ,     , 0                                   , ())                    \
  _(BOOLEAN                         , PickerAudioAssist       ,     , FALSE                               , ())                    \
  _(OC_STRING                       , PickerMode              ,     , OC_STRING_CONSTR ("Builtin", _, __) , OC_DESTR (OC_STRING) ) \
  _(BOOLEAN                         , PollAppleHotKeys        ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , ShowPicker              ,     , FALSE                               , ())                    \
  _(UINT32                          , TakeoffDelay            ,     , 0                                   , ())                    \
  _(UINT32                          , Timeout                 ,     , 0                                   , ())
  OC_DECLARE (BH_MISC_BOOT)

// STRUCT parent=struct
#define BH_MISC_DEBUG_FIELDS(_, __) \
  _(BOOLEAN                         , AppleDebug              ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , ApplePanic              ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , DisableWatchDog         ,     , FALSE                               , ())                    \
  _(UINT32                          , DisplayDelay            ,     , 0                                   , ())                    \
  _(UINT64                          , DisplayLevel            ,     , 0                                   , ())                    \
  _(BOOLEAN                         , SerialInit              ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , SysReport               ,     , FALSE                               , ())                    \
  _(UINT32                          , Target                  ,     , 0                                   , ())
  OC_DECLARE (BH_MISC_DEBUG)

// STRUCT parent=array xref=BH_MISC_TOOLS_ENTRY
// ARRAY of=struct parent=struct xref=BH_MISC_TOOLS_ARRAY
// STRUCT parent=struct
#define BH_MISC_SECURITY_FIELDS(_, __) \
  _(BOOLEAN                         , AllowNvramReset         ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , AllowSetDefault         ,     , FALSE                               , ())                    \
  _(UINT64                          , ApECID                  ,     , 0                                   , ())                    \
  _(BOOLEAN                         , AuthRestart             ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , BlacklistAppleUpdate    ,     , FALSE                               , ())                    \
  _(OC_STRING                       , BootProtect             ,     , OC_STRING_CONSTR ("None", _, __)    , OC_DESTR (OC_STRING) ) \
  _(OC_STRING                       , DmgLoading              ,     , OC_STRING_CONSTR ("Signed", _, __)  , OC_DESTR (OC_STRING) ) \
  _(BOOLEAN                         , EnablePassword          ,     , FALSE                               , ())                    \
  _(UINT32                          , ExposeSensitiveData     ,     , OCS_EXPOSE_VERSION                  , ())                    \
  _(UINT64                          , HaltLevel               ,     , 0x80000000                          , ())                    \
  _(UINT8                           , PasswordHash            , [64] , {0}                                , ())                    \
  _(OC_DATA                         , PasswordSalt            ,     , OC_EDATA_CONSTR (_, __)             , OC_DESTR (OC_DATA)   ) \
  _(UINT32                          , ScanPolicy              ,     , OC_SCAN_DEFAULT_POLICY              , ())                    \
  _(OC_STRING                       , SecureBootModel         ,     , OC_STRING_CONSTR ("Default", _, __) , OC_DESTR (OC_STRING) ) \
  _(OC_STRING                       , Vault                   ,     , OC_STRING_CONSTR ("Secure", _, __)  , OC_DESTR (OC_STRING) )
  OC_DECLARE (BH_MISC_SECURITY)

// STRUCT parent=array
#define BH_MISC_TOOLS_ENTRY_FIELDS(_, __) \
  _(OC_STRING                       , Arguments               ,     , OC_STRING_CONSTR ("", _, __)        , OC_DESTR (OC_STRING) ) \
  _(BOOLEAN                         , Auxiliary               ,     , FALSE                               , ())                    \
  _(OC_STRING                       , Comment                 ,     , OC_STRING_CONSTR ("", _, __)        , OC_DESTR (OC_STRING) ) \
  _(BOOLEAN                         , Enabled                 ,     , FALSE                               , ())                    \
  _(OC_STRING                       , Name                    ,     , OC_STRING_CONSTR ("", _, __)        , OC_DESTR (OC_STRING) ) \
  _(OC_STRING                       , Path                    ,     , OC_STRING_CONSTR ("", _, __)        , OC_DESTR (OC_STRING) ) \
  _(BOOLEAN                         , RealPath                ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , TextMode                ,     , FALSE                               , ())
  OC_DECLARE (BH_MISC_TOOLS_ENTRY)

// ARRAY of=struct parent=struct
#define BH_MISC_TOOLS_ARRAY_FIELDS(_, __) \
  OC_ARRAY (BH_MISC_TOOLS_ENTRY, _, __)
  OC_DECLARE (BH_MISC_TOOLS_ARRAY)

// STRUCT parent=struct
#define BH_MISC_CONFIG_FIELDS(_, __) \
  _(BH_MISC_BLESS_ARRAY             , BlessOverride           ,     , OC_CONSTR2 (BH_MISC_BLESS_ARRAY, _, __)    , OC_DESTR (BH_MISC_BLESS_ARRAY))    \
  _(BH_MISC_BOOT                    , Boot                    ,     , OC_CONSTR2 (BH_MISC_BOOT, _, __)           , OC_DESTR (BH_MISC_BOOT))           \
  _(BH_MISC_DEBUG                   , Debug                   ,     , OC_CONSTR2 (BH_MISC_DEBUG, _, __)          , OC_DESTR (BH_MISC_DEBUG))          \
  _(BH_MISC_TOOLS_ARRAY             , Entries                 ,     , OC_CONSTR2 (BH_MISC_TOOLS_ARRAY, _, __)    , OC_DESTR (BH_MISC_TOOLS_ARRAY))    \
  _(BH_MISC_SECURITY                , Security                ,     , OC_CONSTR2 (BH_MISC_SECURITY, _, __)       , OC_DESTR (BH_MISC_SECURITY))       \
  _(BH_MISC_TOOLS_ARRAY             , Tools                   ,     , OC_CONSTR2 (BH_MISC_TOOLS_ARRAY, _, __)    , OC_DESTR (BH_MISC_TOOLS_ARRAY))
  OC_DECLARE (BH_MISC_CONFIG)

/**
  NVRAM section
**/

///
/// NVRAM values is an associative map of GUIDS with their property key value maps.
///
// MAP of=map
#define BH_NVRAM_ADD_MAP_FIELDS(_, __) \
  OC_MAP (OC_STRING, OC_ASSOC, _, __)
  OC_DECLARE (BH_NVRAM_ADD_MAP)

// ARRAY of=string parent=map
#define BH_NVRAM_DELETE_ENTRY_FIELDS(_, __) \
  OC_ARRAY (OC_STRING, _, __)
  OC_DECLARE (BH_NVRAM_DELETE_ENTRY)

// MAP of=array
#define BH_NVRAM_DELETE_MAP_FIELDS(_, __) \
  OC_MAP (OC_STRING, BH_NVRAM_DELETE_ENTRY, _, __)
  OC_DECLARE (BH_NVRAM_DELETE_MAP)

// ARRAY of=string parent=map
#define BH_NVRAM_LEGACY_ENTRY_FIELDS(_, __) \
  OC_ARRAY (OC_STRING, _, __)
  OC_DECLARE (BH_NVRAM_LEGACY_ENTRY)

// MAP of=array
#define BH_NVRAM_LEGACY_MAP_FIELDS(_, __) \
  OC_MAP (OC_STRING, BH_NVRAM_LEGACY_ENTRY, _, __)
  OC_DECLARE (BH_NVRAM_LEGACY_MAP)

// STRUCT parent=struct
#define BH_NVRAM_CONFIG_FIELDS(_, __) \
  _(BH_NVRAM_ADD_MAP                , Add                     ,     , OC_CONSTR2 (BH_NVRAM_ADD_MAP, _, __)       , OC_DESTR (BH_NVRAM_ADD_MAP))       \
  _(BH_NVRAM_DELETE_MAP             , Delete                  ,     , OC_CONSTR2 (BH_NVRAM_DELETE_MAP, _, __)    , OC_DESTR (BH_NVRAM_DELETE_MAP))    \
  _(BOOLEAN                         , LegacyEnable            ,     , FALSE                               , ())                    \
  _(BOOLEAN                         , LegacyOverwrite         ,     , FALSE                               , ())                    \
  _(BH_NVRAM_LEGACY_MAP             , Legacy                  ,     , OC_CONSTR2 (BH_NVRAM_LEGACY_MAP, _, __)    , OC_DESTR (BH_NVRAM_LEGACY_MAP))    \
  _(BOOLEAN                         , WriteFlash              ,     , FALSE                               , ())
  OC_DECLARE (BH_NVRAM_CONFIG)

/**
  Root configuration
**/

// STRUCT parent=map
#define BH_GLOBAL_CONFIG_FIELDS(_, __) \
  _(BH_CONFIG_CONFIG                , Config                  ,     , OC_CONSTR1 (BH_CONFIG_CONFIG, _, __)       , OC_DESTR (BH_CONFIG_CONFIG))       \
  _(BH_MISC_CONFIG                  , Misc                    ,     , OC_CONSTR1 (BH_MISC_CONFIG, _, __)         , OC_DESTR (BH_MISC_CONFIG))         \
  _(BH_NVRAM_CONFIG                 , Nvram                   ,     , OC_CONSTR1 (BH_NVRAM_CONFIG, _, __)        , OC_DESTR (BH_NVRAM_CONFIG))
  OC_DECLARE (BH_GLOBAL_CONFIG)

/**
  Initialize configuration with plist data.

  @param[out]  Config   Configuration structure.
  @param[in]   Buffer   Configuration buffer in plist format.
  @param[in]   Size     Configuration buffer size.

  @retval  EFI_SUCCESS on success
**/
EFI_STATUS
BhConfigurationInit (
  OUT BH_GLOBAL_CONFIG   *Config,
  IN  VOID               *Buffer,
  IN  UINT32             Size
  );

/**
  Free configuration structure.

  @param[in,out]  Config   Configuration structure.
**/
VOID
BhConfigurationFree (
  IN OUT BH_GLOBAL_CONFIG   *Config
  );

#endif // BH_CONFIGURATION_LIB_H
